name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - ccache
  - cmake
  - cudatoolkit=11.0
  - cudnn=8.0
  - cxx-compiler
  - jupyterlab
  - mpi4py # installs cuda-aware openmpi
  - nccl
  - nvcc_linux-64=11.0
  - openmpi
  - pip
  - pip:
    - tensorflow-gpu==2.4.*
    - -r file:requirements.txt
  - python=3.8
  - tensorboard=2.4

